- R/mod_getData.R
- R/mod_saveData.R
Data Retrieval updates:
1. Allow clearing of selected column in phenotype tab
2. Updated notifications when computing environment column and when loading stored data
4. Added '(*required)' to designation and trait column in phenotype tab; and copied formatting to compute environment button
Save updates:
1. Updated notifications when saving
> Updated Modules: Data Retrieval (column selection and notification) and Save (notification)

- R/mod_oftStaApp.R
- inst/rmd/reportOft.Rmd
OFT report update. I would like to see how it would behave in the deployed version. But I still need to update the viewing of the report. Thank you!
> OFT report update

- inst/rmd/reportSta.Rmd
changed pplotly to plotly. user encountered error in downloading sta report
> fix bug in sta report: pplotly package

- R/mod_singleCrossGenoApp.R
1. Added a condition to check if Genotyic data has been QA/QCed
2. Added a tab in Input to select QA/QC version to use
3. Added an Output tab to show table for computed hybrids and allow downloading of new genotype data
> updated SCM module

- R/app_server.R
- R/app_ui.R
- R/mod_agrAnova.R
- R/mod_oftStaApp.R
- R/mod_reportBuilder.R
- R/mod_sectionInfoAEApp.R
- dev/02_dev.R
- inst/rmd/reportOft.Rmd
- inst/rmd/reportOft.html
- updated OFT report to handle datasets with no disease information
- updated OFT report to include recording of user inputs for regenerate report
- updated analytical module to include regeneration of OFT report
- updated analytical module to include name of module in the file output (ex. my-report-sta.html)
- added the anova in the menu and the mock-up UI (colored red for now since it is not yet working)
> updated OFT report

- inst/rmd/reportSta.Rmd
Using functions round.dt and round.df from cgiarBase to format numbers with 3 significant digits
> formating output numbers with 3 significant digits

- R/mod_qaRawApp.R
Problems:
- outliers table and boxplot doesn’t show outliers when there is only 1.
- outliers table doesn’t show outliers for different traits when in the same row
- outliers table show traits without oultliers and NA values in all columns
> small details with visualization of outliers

- R/mod_oftStaApp.R
- inst/rmd/reportOft.html
> fix select version to use OFT

- inst/rmd/reportOft.Rmd
- inst/rmd/reportOft.html
Changes made to handle errors when:
- trait is not present in all environments
- pedigree file contains many other columns (specially when same as columns in pheno data)
- displaying metrics table because 'mean' was renamed
- scrolling tables horizontally because headers not moving
> Update OFT report

- R/mod_dataConsistPotatoApp.R
- inst/rmd/reportQaPheno.Rmd
mod_dataConsistPotatoApp.R
- avoid printing text in tag outliers screen
- interchange rows and columns in matrix plot
- remove duplicated icon in input tab
reportQaPheno.Rmd
- convert variable to numeric (to show the boxplot)
Important: update st4gi to the last version
> Somo modifications for data consistency

- inst/rmd/reportIndex.Rmd
- inst/rmd/reportMas.Rmd
- inst/rmd/reportMta.Rmd
- inst/rmd/reportMtaFlex.Rmd
- inst/rmd/reportMtaLMMsolver.Rmd
- inst/rmd/reportNeGeno.Rmd
- inst/rmd/reportOcs.Rmd
- inst/rmd/reportPgg.Rmd
- inst/rmd/reportPopStr.Rmd
- inst/rmd/reportQaGeno.Rmd
- inst/rmd/reportQaPheno.Rmd
- inst/rmd/reportRgg.Rmd
- inst/rmd/reportSta.Rmd
- inst/rmd/reportVerifGeno.Rmd
- inst/rmd/reportWeather.Rmd
Updated the RMDs of all reports with printTable function to fix issue with the scroll.
for download: autoWidthOpt = TRUE, scrollXOpt = FALSE
for display in UI: autoWidthOpt = FALSE, scrollXOpt = TRUE
> Update Dashboard tables to fix scroll

- inst/rmd/reportAbi.Rmd
- inst/rmd/reportIndex.Rmd
- inst/rmd/reportMas.Rmd
- inst/rmd/reportMta.Rmd
- inst/rmd/reportMtaFlex.Rmd
- inst/rmd/reportMtaLMMsolver.Rmd
- inst/rmd/reportNeGeno.Rmd
- inst/rmd/reportOcs.Rmd
- inst/rmd/reportOft.Rmd
- inst/rmd/reportPgg.Rmd
- inst/rmd/reportPopStr.Rmd
- inst/rmd/reportQaGeno.Rmd
- inst/rmd/reportQaPheno.Rmd
- inst/rmd/reportRgg.Rmd
- inst/rmd/reportSta.Rmd
- inst/rmd/reportVerifGeno.Rmd
- inst/rmd/reportWeather.Rmd
added DT:: to formatRound function
> added DT:: to formatRound function

- R/app_server.R
- R/app_ui.R
- R/mod_glossary.R
- dev/02_dev.R
- glossary.md
- inst/rmd/glossary.Rmd
Added the module for glossary. It includes both script for:
- reading the glossary from a csv file (active)
- directly editing from the RMarkdown document (commented)
> added the module for glossary

- DESCRIPTION
- R/mod_getDataGeno.R
- R/mod_qaGenoApp.R
- Implementation of read the following formats using genlight class
1. Hapmap (polyploid compatible)
2. VCF (polyploid compatible)
3. DartSeq SNP (Diploid)
4. DartTag SNP (Tetraploid)
- Genotype QA/QC using a step by step filtering approach.
- Creation of imputation tab inside QA/QC module
1. DESCRIPTION
2. R/mod_getDataGeno.R
3. R/mod_qaGenoApp.R
> Implementation of genlight for genotype representation

- R/mod_abiDashboard.R
- inst/rmd/reportAbi.Rmd
- reportAbi.md
1. add analysisIdName = "" in the status to match with other modules.
2. since Vg and Vr are no longer in the metrics parameters I just selected those starting with V
> fix abi dashboard

- R/mod_PopStrApp.R
- R/mod_mtaASREMLApp.R
- inst/rmd/reportMtaASREML.Rmd
I did changes in appearance and for use genlight structure
> Changes for PopStr and asreml module

- R/mod_qaPhenoApp.R
- reportQaPheno.md
This module provides comprehensive correlation analysis for your raw data, allowing you to calculate Pearson, Spearman, and Kendall correlation coefficients, determine statistical significance for each, and view results in graphical formats.
> Correlation matrices

- R/mod_indexBaseApp.R
- inst/rmd/reportIndexB.Rmd
changes made:
- added the new module names being used for mta analysis (mtaLmms, mtaAsr) to get the available analysisId
- added a report file to enable downloading of report (needs help in filling up the objectives)
> update the mta module name and add report file

- R/mod_rggApp.R
changes made:
- parameter input selection depends on method selected
for Mackay: environment = "(Intercept)" and effectType = "designation"; values to use for year (required) and entryType can be selected by user, if entryType is NULL no more filtering will be done with the data
for Piepho: effectType = NULL; values to use for year (required), environment (required) and entryType can be selected by user, if entryType is NULL no more filtering will be done with the data
- updated condition for checking of available data
added sta and mtaAsr since these modules can also be used as data source for this analysis
even if yearOfOrigin column is present, added a condition to check if contents are not equal to "" or NA
- updated conditions for filtering of data. since inputs are multiple, I used …
> fix rgg module

- R/mod_rggApp.R
- inst/rmd/reportMtaLMMsolver.Rmd
I looked at other modules using the ExtendedTask function. Noticed that all of them have been commented out already. some examples are mod_staApp and mod_indexDesireApp. So I decided to remove it as well here. Thank you!
> removed ExtendedTask function definition

- R/mod_staApp.R
change scales to fixed to avoid error in field view visualization
> change scales to fixed to avoid error in field view visualization

- R/mod_bindObjectApp.R
- R/mod_getDataPheno.R
- R/mod_mtaLMMsolveApp.R
- R/mod_qaPhenoApp.R
changes made:
**mod_bindObjectApp**
- fix error in network plot when no analysis has been done yet
**mod_getDataPheno**
- added information on how environment column is being computed/formed
**mod_mtaLMMsolveApp**
- added information on popular genetic evaluation models and surrogate of merit
**mod_qaPhenoApp**
- modified the UI of correlation plot to match with other modules
> added information and fix plot

- R/app_server.R
- R/app_ui.R
- R/mod_CoreSubsetApp.R
- inst/rmd/reportCoreSet.Rmd
- inst/rmd/reportMtaASREML.Rmd
Change report for asreml module for show genetic correlation
Add module and report for Pop-subset module
> Changes for asreml module

- R/mod_PopStrApp.R
- R/mod_abiDashboard.R
- R/mod_bindObjectApp.R
- R/mod_getDataPheno.R
- R/mod_gpcpApp.R
- R/mod_gwasqkApp.R
- R/mod_hybridityApp.R
- R/mod_indexBaseApp.R
- R/mod_indexDesireApp.R
- R/mod_masApp.R
- R/mod_mtaASREMLApp.R
- R/mod_mtaLMMsolveApp.R
- R/mod_ocsApp.R
- R/mod_oftStaApp.R
- R/mod_pggApp.R
- R/mod_qaGenoApp.R
- R/mod_qaPhenoApp.R
- R/mod_qaStaApp.R
- R/mod_reportBuilder.R
- R/mod_rggApp.R
- R/mod_staApp.R
- inst/rmd/reportAbi.Rmd
- inst/rmd/reportMas.Rmd
- inst/rmd/reportRgg.Rmd
As suggested by Khaled, we can use this function to create an empty data object.
> create empty data object when loading old analysis
